name: Release Workflow

on:
  release:
    types:
      - created

jobs:
  release-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get release tag
      run: echo "Release tag is ${{ github.event.release.tag_name }}"
