name: Release Images and Charts

on:
  release:
    types:
      - "created"

jobs:
  pre-checks:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Docker CLI for GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Check if Docker image is available
        run: |
          IMAGE=ghcr.io/abhinandan-purkait/dev/zfs-driver:${{ github.ref_name }}
          echo "Checking image: $IMAGE"
          if ! docker buildx imagetools inspect "$IMAGE" > /dev/null 2>&1; then
            echo "❌ Docker image $IMAGE not found on GHCR"
            exit 1
          fi

      - name: Check if Helm chart is available
        run: |
          CHART_REF=oci://ghcr.io/abhinandan-purkait/helm/zfs-localpv
          echo "Checking chart: $CHART_REF --version ${{ github.ref_name }}"
          if ! helm pull "$CHART_REF" --version "${{ github.ref_name }}" > /dev/null 2>&1; then
            echo "❌ Helm chart version ${{ github.ref_name }} not found in GHCR"
            exit 1
          fi

      - name: Install Skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Mirror zfs-driver image to Docker Hub & Quay
        env:
          SRC: ghcr.io/abhinandan-purkait/dev/zfs-driver:${{ github.ref_name }}
          DH_DEST: docker://docker.io/abhinandan15/zfs-driver:${{ github.ref_name }}
          # QY_DEST: docker://quay.io/${{ env.IMAGE_ORG }}/zfs-driver:${{ github.ref_name }}
          # GH_DEST: docker://ghcr.io/${{ env.IMAGE_ORG }}/zfs-driver:${{ github.ref_name }}
        run: |
          skopeo copy \
            --src-creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
            --dest-creds "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" \
            "docker://${SRC#docker://}" "$DH_DEST"

      - name: Set up Helm CLI
        uses: azure/setup-helm@v3

      - name: Log in to GHCR for Helm
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u abhinandan-purkait --password-stdin

      - name: Pull OCI chart from GHCR
        run: |
          CHART_REF=oci://ghcr.io/abhinandan-purkait/helm/zfs-localpv
          mkdir -p charts-staged
          helm pull "$CHART_REF" \
            --version "${{ github.ref_name }}" \
            --destination charts-staged

      - name: Publish chart via helm-gh-pages
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: ./charts-staged

# skopeo copy \
#   --src-creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
#   --dest-creds "${{ secrets.QUAY_USERNAME }}:${{ secrets.QUAY_TOKEN }}" \
#   "$SRC" "$QY_DEST"

# skopeo copy \
#   --src-creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
#   --src-creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
#   "$SRC" "$GH_DEST"
